### ISSUE TITLE
Add `license` field to `pyproject.toml`

### ISSUE THREAD

**Issue by JamieMagee** [Genie-Garage/aladdin-python-sdk#1]
The `LICENSE` file is shipped in the package, adding a `license` field to your `pyproject.toml` will make it visible on [your PyPI page][1]. See [the `pyproject.toml` documentation for more information][2].

[1]: https://pypi.org/project/genie-partner-sdk/
[2]: https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license

**Comment by swcloudgenie** [comment]
I have added this field
